### PR TITLE
Introduce helpers for consistent style: welcome black and pre-commit

### PR DESCRIPTION
**Pull request by ctheune**
This introduces helpers for a consistent coding style. I have used the template from my company 
which allows local customization and can be used to update the style in the future:

https://github.com/flyingcircusio/codestyle-template/

The Github Action likely needs you to press a couple of knobs in the UI to allow them to run - not sure about that though.

### CODE REVIEW

**Comment by davidolrik** [comment]
Nice! - Thanks for that!

If you change the line length to 130, I'll merge it =)

**Comment by ctheune** [comment]
Oh, 130. Interesting. But yeah. Happy to oblige.

**Comment by ctheune** [comment]
There you go.

I don't want to bikeshed, so please feel free to ignore me: I'm from the faction of "79/80 or less" not because of "old terminals are cool", but because I buy into the typographic arguments that lines longer than 60-80 characters become hard to read and line tracking for the eyes becomes much harder.

Again, feel free to ignore to avoid bikeshedding. :)

**Comment by davidolrik** [comment]
> There you go.

👍🏽

> I don't want to bikeshed, so please feel free to ignore me: I'm from the faction of "79/80 or less" not because of "old terminals are cool", but because I buy into the typographic arguments that lines longer than 60-80 characters become hard to read and line tracking for the eyes becomes much harder.

I'm in the I bought this nice big monitor and damn it I'm gonna use it! 😁
I also agree with the those typographic arguments, but at a a slightly higher line length, given that there are syntax colouring and other such aids.

> Again, feel free to ignore to avoid bikeshedding. :)

Consider it so ignored 😊

**Pull request merged**
